name: check dbt version and installation

on:
  workflow_dispatch:
  push:
    paths:
      - 'dbt_project/**'
  # schedule:
  #   - cron:  '*/15 * * * *'

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-run
        id: dbt-run
        uses: ./
        with:
          dbt_command: "dbt --version"
          dbt_project_folder: "dbt_project"
      - name: Get the result
        run: echo "${{ steps.dbt-run.outputs.result }}"
        shell: bash
